### ISSUE TITLE
Why AssetRootPath is not a Dependency Property?

### ISSUE THREAD

**Issue by SuperJMN** [whistyun/MdXaml#12]
If the MarkdownScrollViewer.Markdown property is set before AssetsRootPath, the URIs of the images won't get the correct path.

**Comment by whistyun** [comment]
A value which is set`MarkdownScrollViewer.AssetPathRoot` (including BaseUri) property is set `Markdown.AssetPathRoot` directly.
So if `MarkdownScrollViewer.Mardown` property is set **after** `AssetsRootPath`, MdXaml try to access unexpected file path.

I will fix the behavior change in the order I set, but I'm not sure that it will solve your issues.

If possible, show me your code.

**Comment by whistyun** [comment]
@SuperJMN 
I'm really sorry. I misunderstood the Markdown property as the Markdown class(Engine property).

In ver1.7.0, when AssetPathRoot is set, Markdown is remaked and load image from correctly path.
And I changed AssetRootPath as DependencyProperty, So we can change this property with Binding.

**Comment by SuperJMN** [comment]
Thanks for the quick fix!
