### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by murashov-a** [whistyun/MdXaml#25]
Hi! Please help me.

If insert `[test](test)` and clicked, catch exception **file not found** (`System.ComponentModel.Win32Exception`)

My xaml:
```XAML
<Style TargetType="xaml:MarkdownScrollViewer" x:Key="MarkdownScrollViewerStyle">
    <Style.Setters>
        <Setter Property="BorderThickness" Value="0" />
        <Setter Property="Background" Value="Transparent" />
        <Setter Property="HorizontalAlignment" Value="Stretch" />
        <Setter Property="VerticalAlignment" Value="Stretch" />
        <Setter Property="VerticalScrollBarVisibility" Value="Disabled" />
        <Setter Property="HorizontalScrollBarVisibility" Value="Auto" />
        <Setter Property="MarkdownStyle" Value="{x:Static xaml:MarkdownStyle.Standard}" />
    </Style.Setters>
</Style>

...

<xaml:MarkdownScrollViewer
    Style="{StaticResource MarkdownScrollViewerStyle}"
    Markdown="{Binding Text}"
    ClickAction="OpenBrowser" />
```

It's bad if user can crash the program in the user interface.

please, help me. How can I fix this?

**Comment by whistyun** [comment]
If you want your custom scheme, you should write it like as `[test](yours://test)` or `[test](yours:test)`.
MdXaml with OpenBrowser behaves like Win+r.

> The link can lead to a custom protocol or a link to a file on a network drive :-(

Did you mean that you want a mechanism to change the relative path to the absolute path?
For example, the new property `LinkPathRoot`  will be used as the base path for relative link paths.

**Comment by murashov-a** [comment]
I understand this, but the users of my application may not understand.  
How do I handle this type of input error?  

If you enter "test" in the win+r, it will give an error that the "test" application cannot be found, and the library hangs or throws an exception that cannot be handled in any way
