### ISSUE TITLE
Upgrade to AvalonEdit 6

### ISSUE THREAD

**Issue by Khaos66** [whistyun/MdXaml#26]
It would be nice if you could upgrade to AvalonEdit 6 (current is 6.1.2.30)
I'll fork this repo now to get it working for me ;)

EDIT: I meant for .NET Framework. As you already use AvalonEdit 6 for .net-5

**Comment by whistyun** [comment]
I upgrade to AvalonEdit 6, and release v1.12.0.

**Comment by Khaos66** [comment]
Wow that's fast! Thank you very much
