### ISSUE TITLE
How to make links clickable?

### ISSUE THREAD

**Issue by wojciechsura** [whistyun/MdXaml#28]
Having the following markdown: `[Google](https://google.com)` ( => [Google](https://google.com) ), the link is properly styled, but doesn't show the hand icon and in general doesn't work. How one can make the links clickable?

**Comment by whistyun** [comment]
You need to set `ClickAction` property like the following
```xml
<!-- xmlns:mdxam="clr-namespace:MdXaml;assembly=MdXaml" -->
<mdxam:MarkdownScrollViewer
        ClickAction="OpenBrowser"
        />
```
for more imformation, to see [this document](https://github.com/whistyun/MdXaml/wiki/How-to-customise-linkaction).

**Comment by wojciechsura** [comment]
Missed this. Thanks :)
