### ISSUE TITLE
Copying a text containing a Hyperlink to clipboard causes an unhandled exception

### ISSUE THREAD

**Issue by isbeorn** [whistyun/MdXaml#29]
Hi,
the MarkdownScrollViewer has a small issue when using Hyperlinks and runs into an unhandled exception when involving the clipboard.

Steps to reproduce
- Start the "WithFluentWPF sample app
- On the rendered Markdown on the right side scroll down to "Link to Google"
- Mark some text including the hyperlink
- Push ctrl+c to copy it to clipboard

Actual Behavior
- The copy action fails as it tries to serialize the nested OpenCommand class and runs into an unhandled exception: "Cannot serialize a non-public type 'MdXaml.MarkdownScrollViewer+OpenCommand'. "

Expected Behavior
- No errors occur

Possible Fix
- Moving the OpenCommand class outside of the nested structure to be a top level will prevent this error from happening

**Comment by whistyun** [comment]
I released [v1.13.0](https://github.com/whistyun/MdXaml/releases/tag/v1.13.0) to fix this issue.

**Comment by isbeorn** [comment]
Works like a charm. Thank you.
