### ISSUE TITLE
Remote images mostly not showing

### ISSUE THREAD

**Issue by lars-29palms** [whistyun/MdXaml#32]
Hey first of all thanks for this great package!

Everything seems to be working nicely, including custom styling. The only issue I'm facing thus far:

Remote images are mostly not working, and there is no general rule what is working and what isn't.
For example this image always shows:
```txt
![image](https://getcontrail.com/images/icon-32px.png)
```

This one only showed up once, otherwise it's just an empty space:
```txt
![image](https://cdn.29palms.de/api/img/developer/f585a34c2b81b5b1bff1fcf51e4e151b.jpg)
```

The markdown is data bound to a property.
Is there a way to debug this?

**Comment by whistyun** [comment]
Thanks for issues. 

I released v1.14.0. This version fix the issue that a same image can't be displayed in multiple places.
If this is not the problem you are facing, please reply.
