### ISSUE TITLE
Referenced assembly 'MdXaml, Version=1.16.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.

### ISSUE THREAD

**Issue by Kozzba** [whistyun/MdXaml#41]
When I append to MarkdownScrollViewer attribute Name, it throws a warning: 
_Referenced assembly 'MdXaml, Version=1.16.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name._ 
Without attribute Name its OK. This warning cause another errors in my app ..

**Comment by whistyun** [comment]
The new version 1.16.1 is released.
This package is signed to have strong name.
