### ISSUE TITLE
how to set Background and Foreground color ?

### ISSUE THREAD

**Issue by LauraKami** [whistyun/MdXaml#46]
As soon I try to force Background and Foreground Color, the Style don't work anymore, no more heading, etc ...  
Image always work fine.

What I can make wrong ?

```
           Markdown engine1 = new Markdown();
            Markdown engine2 = new Markdown();
            Markdown engine3 = new Markdown();


            string markdownTxt = System.IO.File.ReadAllText("example.md");
            FlowDocument document1 = engine1.Transform("# 1 Sasabune\n\n\n\n"+markdownTxt);
            FlowDocument document2 = engine2.Transform("# 2 SasabuneCompact\n\n\n\n" + markdownTxt);
            FlowDocument document3 = engine3.Transform("# 3 SasabuneStrandard\n\n\n\n" + markdownTxt);
            FlowDocument document4 = engine3.Transform("# 4 SasabuneStandard\n\n\n\n" + markdownTxt);

            document1.Background = new SolidColorBrush( Color.FromArgb(255, 0, 0, 0));
            document1.Foreground = new SolidColorBrush( Color.FromArgb(255, 255, 250, 250));
            document1.Style = MarkdownStyle.Sasabune;

            document2.Background = new SolidColorBrush(Color.FromArgb(255, 0, 0, 0));
            document2.Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 250, 250));
            document2.Style = MarkdownStyle.SasabuneCompact;

            document3.Background = new SolidColorBrush(Color.FromArgb(255, 0, 0, 0));
            document3.Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 250, 250));
            document3.Style = MarkdownStyle.SasabuneStandard;

            //document4.Background = new SolidColorBrush(Color.FromArgb(255, 0, 0, 0));
            //document4.Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 250, 250));
            document4.Style = MarkdownStyle.SasabuneStandard;

            FDPageViewver.Document = document1;  // FD=FlowDocument
            FDReader.Document = document2;
            FDSV.Document = document3;  
            MSV.Document = document4;  // MSV=MarkdowScrollViewer

```

**Comment by whistyun** [comment]
For now, `Sasabune***` style only works on `MarkdownScrollViewer`.
And It don't references FlowDocument properties but `MarkdownScrollViewer` properties.

```cs
Markdown engine = new();
FlowDocument document = engine.Transform("# Heading1\n## Heading2\n### Heading3\n#### Heading3\nfoo bar text\n|head1|head2|\n|-|-|\n|body1|body2|");
document.Style = MarkdownStyle.SasabuneStandard;

// MarkdownScrollViewer MSV = new();
MSV.Document = document;
MSV.Background = new SolidColorBrush(Color.FromArgb(255, 0, 0, 0));
MSV.Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 255, 255));
```
![image](https://user-images.githubusercontent.com/13712028/202833733-142630b6-d6e6-41a9-9e2d-a82bac4a6a9c.png)

**Comment by LauraKami** [comment]
![2022-11-22 15_38_56-Clipboard](https://user-images.githubusercontent.com/102795992/203328253-6b27aee3-f460-4f3d-8f4c-1cdf031ce026.png)

as soon, I have style, Header 1 2 3 don't work anymore for me,
 only R0C0 with no style ( style in Xaml, but don't work header is not red or blue ).


![2022-11-22 15_46_07-WpfAppMdDemo2 - Microsoft Visual Studio](https://user-images.githubusercontent.com/102795992/203329767-96e64140-00b3-405e-8cca-0ada2ce4745a.png)

`
            Markdown engine = new();

            //string markdownTxt = "";
            string markdownTxt = "# Heading1\n## Heading2\n### Heading3\n#### Heading3\nfoo bar text\n|head1|head2|\n|-|-|\n|body1|body2|";
            //string markdownTxt = System.IO.File.ReadAllText("example.md");
            FlowDocument document1 = engine.Transform("# Heading1\n## Heading2\n# 1-R0C0 Style XAML\n" + markdownTxt);
            FlowDocument document2 = engine.Transform("# Heading1\n## Heading2\n# 2-R1C0 Sasabune\n" + markdownTxt);
            FlowDocument document3 = engine.Transform("# Heading1\n## Heading2\n# 3-R0C1 SasabuneCompact\n" + markdownTxt);
            FlowDocument document4 = engine.Transform("# Heading1\n## Heading2\n# 4-R1C1 SasabuneStandard\n" + markdownTxt);


            // Document.Style = MarkdownStyle.Sasabune;  ( style in xaml )
            MSV_R0C0.Document = document1;
            MSV_R0C0.Document.Background = new SolidColorBrush( Color.FromArgb(255, 0, 0, 0)); // a,r,g,b
            MSV_R0C0.Document.Foreground = new SolidColorBrush( Color.FromArgb(255, 255, 255,255));


            
            document2.Style = MarkdownStyle.Sasabune;
            MSV_R1C0.Document = document2;
            MSV_R1C0.Document.Background = new SolidColorBrush(Color.FromArgb(255, 0, 0, 0));
            MSV_R1C0.Document.Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 255, 255));

            document3.Style = MarkdownStyle.SasabuneCompact;
            MSV_R0C1.Document = document3;
            MSV_R0C1.Document.Background = new SolidColorBrush(Color.FromArgb(255, 0, 0, 0));
            MSV_R0C1.Document.Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 255, 255));

            document4.Style = MarkdownStyle.SasabuneStandard;
            MSV_R1C1.Document = document4;
            MSV_R1C1.Document.Background = new SolidColorBrush(Color.FromArgb(255, 0, 0, 0));
            MSV_R1C1.Document.Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 255, 255));
`

`
        xmlns:mdxam="clr-namespace:MdXaml;assembly=MdXaml"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800"
        Loaded="Window_Loaded">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="50*"/>
            <RowDefinition Height="50*"/>
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="50*"/>
            <ColumnDefinition Width="50*"/>
        </Grid.ColumnDefinitions>
        <Grid.Resources>
            <Style x:Key="MdStyle" TargetType="FlowDocument">
                <Style.Resources>
                    <Style TargetType="Paragraph">
                        <Style.Triggers>
                            <Trigger Property="Tag" Value="Heading1">
                                <Setter Property="FontSize"   Value="42" />
                                <Setter Property="Foreground" Value="Red" />
                                <Setter Property="FontWeight" Value="Light" />
                            </Trigger>
                            <Trigger Property="Tag" Value="Heading2">
                                <Setter Property="FontSize"   Value="20" />
                                <Setter Property="Foreground" Value="Blue" />
                                <Setter Property="FontWeight" Value="Light" />
                            </Trigger>
                        </Style.Triggers>
                    </Style>
                </Style.Resources>
            </Style>

        </Grid.Resources>
        <mdxam:MarkdownScrollViewer 
            x:Name="MSV_R0C0"
            Grid.Row="0" Grid.Column="0"
            MarkdownStyle="{StaticResource ResourceKey=MdStyle}"
            xml:space="preserve">
                # Heading R0C0

                ## Heading 2

                content
        </mdxam:MarkdownScrollViewer>
        <mdxam:MarkdownScrollViewer 
            x:Name="MSV_R1C0"
            Grid.Row="1" Grid.Column="0"
            
            xml:space="preserve">
                # Heading R1C0

                ## Heading 2

                content
        </mdxam:MarkdownScrollViewer>
        <mdxam:MarkdownScrollViewer 
            x:Name="MSV_R0C1"
            Grid.Row="0" Grid.Column="1"
            xml:space="preserve">
                # Heading R0C1

                ## Heading 2

                content
        </mdxam:MarkdownScrollViewer>
        <mdxam:MarkdownScrollViewer 
            x:Name="MSV_R1C1"
            Grid.Row="1" Grid.Column="1"
            xml:space="preserve">
                # Heading R1C1

                ## Heading 2

                content
        </mdxam:MarkdownScrollViewer>
    </Grid>

</Window>
`

![2022-11-22 15_43_10-WpfAppMdDemo2 - Microsoft Visual Studio](https://user-images.githubusercontent.com/102795992/203329044-27fd479d-3554-426e-a6c9-010ede612d7a.png)

**Comment by whistyun** [comment]
Please modify your code as the bellow.

```cs
MSV_R0C0.Document = document1;
MSV_R0C0.Background = new SolidColorBrush( Color.FromArgb(255, 0, 0, 0)); // a,r,g,b
MSV_R0C0.Foreground = new SolidColorBrush( Color.FromArgb(255, 255, 255,255));

document2.Style = MarkdownStyle.Sasabune;
MSV_R1C0.Document = document2;
MSV_R1C0.Background = new SolidColorBrush(Color.FromArgb(255, 0, 0, 0));
MSV_R1C0.Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 255, 255));

document3.Style = MarkdownStyle.SasabuneCompact;
MSV_R0C1.Document = document3;
MSV_R0C1.Background = new SolidColorBrush(Color.FromArgb(255, 0, 0, 0));
MSV_R0C1.Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 255, 255));

document4.Style = MarkdownStyle.SasabuneStandard;
MSV_R1C1.Document = document4;
MSV_R1C1.Background = new SolidColorBrush(Color.FromArgb(255, 0, 0, 0));
MSV_R1C1.Foreground = new SolidColorBrush(Color.FromArgb(255, 255, 255, 255));
```

Sasabune***(Sasabune, SasabuneCompact and SasabuneStandard) refers only to the direct properties of MarkdownScrollViewer.

**Comment by LauraKami** [comment]
merci @whistyun 
Yes it's work fine, sorry I don't see in your first post, the subtle difference between set at document level vs set at Viewer level.
Have a good day.
Laura
