### ISSUE TITLE
Bolding first word in unordered list not rendering correctly

### ISSUE THREAD

**Issue by CBeatt13** [whistyun/MdXaml#52]
I'm attempting to create an unordered list where the first word is bold like so:

- **Bold Header**: Details

Using the following markdown:

`* **Bold Header**: Details`

But the render engine fails to do so properly. I could use the hyphen to do the unordered list like most markdown engines I've used in the past, but I don't really like the open bullet used and am unsure how to change it out.

**Comment by CBeatt13** [comment]
I also tried the following code to overwrite the markdown style in hopes of changing the List MarkerStyle but was unsuccessful

`<Style TargetType="List">
    <Setter Property="Margin" Value="0"/>
    <Setter Property="MarkerStyle" Value="Square"/>
</Style>`

**Comment by whistyun** [comment]
Sorry, this is parsing issue.
I have released v1.16.3 to solve this issue.

Please update her MdXaml package on your project.

**Comment by CBeatt13** [comment]
Thanks for taking a look at it. I'll pull down the new package and let you know if I see it resolved. Will probably be several hours before I can let you know. Feel free to close the ticket in the meantime if you wish.
