### ISSUE TITLE
Document is null in class constructor

### ISSUE THREAD

**Issue by rocksdanister** [whistyun/MdXaml#54]
Document get returns null in class constructor but its possible to access Document outside it.

Sample code:
```xml
<mdxam:MarkdownScrollViewer x:Name="markdown" ../>
```
```cs

public Sample()
{
  markdown.Document.Blocks.Add(new Paragraph("Null exception")));
}

public void SomeFn()
{
  markdown.Document.Blocks.Add(new Paragraph("This works")));
}
```

**Comment by whistyun** [comment]
Has a code which access Document property been tried [here](https://github.com/rocksdanister/lively/blob/598fbd9b138c27ce7494191b714f9f07254a8a64/src/Lively/Lively/Views/AppUpdater.xaml.cs#L42)?

The initial value of Document property is null for now. And this vlaue is not changed until the Source or Markdown property value is changed.

MarkdownScrollViewer inherits from FlowDocumentScrollViewer. So the Document property can be initialized.

```cs
markdown.Document = new FlowDocument(new Paragraph(new Run("some text")));
```

Be careful not to change the Markdown and Source properties. These properties will update Document property.

**Comment by rocksdanister** [comment]
Yes, It was old code from when using RichTextBox.

Maybe make Document setter private? initially being null before Markdown or Source can lead to mistakes like this.

**Comment by whistyun** [comment]
The private access level prevents access to Document property.

I plan to change the Document getter so that it does not return null (it is automatically initialized).

```cs
public class MarkdownScrollViewer : FlowDocumentScrollViewer, IUriContext
{

    ・・・

    public new FlowDocument? Document
    {
        get
        {
            var bs = (FlowDocumentScrollViewer)this;
            return bs.Document ??= new FlowDocument();
        }
        set => ((FlowDocumentScrollViewer)this).Document = value;
    }
}
```

This is not an override, but hides accessible base property.
So if MarkdownScrollViewer is cast to FlowDocumentScrollViewer, the problem recurs.

```cs

var viewer1= new MarkdownScrollViewer();
viewer1.Document.Blocks.Add(...);  // No error occurres.

var viewer2 = (FlowDocumentScrollViewer)new MarkdownScrollViewer();
viewer2.Document.Blocks.Add(...);  // NullReferenceException occures
```

Would this amendment help you?

**Comment by rocksdanister** [comment]
I think this is fine.

**Comment by whistyun** [comment]
v1.17.0 has be released.
The Document does not return null (it is automatically initialized).

**Comment by rocksdanister** [comment]
Great, I'll close this 🥳
