### ISSUE TITLE
Table of contents or links to anchors

### ISSUE THREAD

**Issue by LevYas** [whistyun/MdXaml#57]
Hi! Thank you for a great library.
Is it possible to navigate on a page with a link to anchors?
I tried this https://stackoverflow.com/a/27953547/3087417 but clicking on a link with ClickAction="OpenBrowser" leads to a fatal exception. With ClickAction="DisplayWithRelativePath" it displays the library definition and XAML code of the control or something like that.

**Comment by whistyun** [comment]
[v1.18.1](https://github.com/whistyun/MdXaml/releases/tag/v1.18.1) has be released.

This version enable link to anchors.
This feature is enabled when MarkdownScrollViewer.ClickAction is set to OpenBrowser, DisplayWithRelativePath or DisplayAll.
Anchor generation rules are the same as for Markdig.

```md
* [Heading1](#heading-1)
* [Heading with link](#heading-with-link)
* [Tag has id attribute](#test)

## Heading (1)

## [Heading with link](https://google.com)

<h2 id="test">Tag has id attribute</h2>
```
